### ISSUE TITLE
dash depends on genproto.bzl

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/dash#12]
It is now broken at HEAD because 285112c9b61ca3782e00ccf6411339da7291a3c3 removed it from the embedded_source.

Dash should probably use bazel as a remote repository 

/cc @kchodorow @lberki

**Comment by lberki** [comment]
(Sigh)

Unfortunately, that doesn't work, because then the implicit dependencies would be all wrong, because they refer to the main repository. I kind of remember that we had this problem, but the only "solution" I see is `REPOSITORY_NAME`, which is the exact wrong thing, because what I need is the name of the repository the .bzl file is in (both in macros and in Skylark rules)

Do y'all remember what we came up for that? 

/cc @laurentlb

**Comment by damienmg** [comment]
As said offline: `str(Label('//lbl'))`

**Comment by lberki** [comment]
Fixed in https://github.com/bazelbuild/dash/commit/4ca8e6e9c3b00894019b0a610bf2dceab46ee9f6 .
